### PR TITLE
Adding enviroment files

### PR DESCRIPTION
**Pull request by akshitac8**
Adding anaconda environment for easy use of the toolkit

### CODE REVIEW

**Comment by srush** [comment]
Sorry, I'm actually not going to accept this, it is overkill. If people want to use anaconda they can just use the requirements, or we can make a setup.cfg. That is all most open-source projects do.

**Comment by akshitac8** [comment]
oh okay @srush, Thank you for the reviews.

**Comment by akshitac8** [comment]
Should I Upload a setup.cfg instead of this approach?

**Comment by srush** [comment]
if you feel that is important and it doesn't duplicate requirements.txt you can upload it.

**Comment by akshitac8** [comment]
Okay, Thank you for the response :)

**Pull request closed without merging**
